<?php
// Set doctype explicitly if it is not `HTML4_LOOSE`, i.e. 'HTML 4.01 Transitional'
$this->doctype('HTML5');

// Load translation data
$this->i18nTheme();

//HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
$this->js(array(
    pi::url('static/js/html5shiv.js') => array(
        'conditional' => 'lt IE 9'
    ),
    pi::url('static/js/respond.min.js') => array(
        'conditional' => 'lt IE 9'
    ),
));

// Load jQuery
$this->jquery();

// Load Bootstrap css/js and font-awesome
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'font-awesome/css/font-awesome.min.css'
));

// Load front.css
$this->css(array(
    $this->assetTheme('css/front.css'),
    //$this->assetTheme('css/animate.css'),
));

// Load localization css
$this->css($this->assetLocale('locale.css'));

// Load front.js on footer
$this->footScript()->appendFile($this->assetTheme('js/front.js'));

// Apple icons
// Apple icon for iphone
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'href'  => $this->assetTheme('image/touch-icon-iphone.png')
));
// Apple icon for ipad
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '72x72',
    'href'  => $this->assetTheme('image/touch-icon-ipad.png')
));
// Apple icon for iphone retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-iphone-retina.png')
));
// Apple icon for ipad retina
$this->headLink(array(
    'rel'   => 'apple-touch-icon',
    'sizes' => '114x114',
    'href'  => $this->assetTheme('image/touch-icon-ipad-retina.png')
));

// Meta Viewport Tag
$this->headMeta('width=device-width, initial-scale=1.0', 'viewport');

// Explicitly load favicon
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/x-icon',
    'href'  => $this->favicon(),
));
$this->headLink(array(
    'rel'   => 'shortcut icon',
    'type'  => 'image/png',
    'href'  => $this->favicon('favicon.png'),
));

// Load google analytics code
$this->ga();

// Get module name
$module = Pi::service('module')->current();

// Get navigation
$navigation = $this->nav('front');

// Get block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

// Get breadcrumbs
$breadcrumbs = $this->breadcrumb(
    array('prefix' => array(
        array(
            'label' => __('Home'),
            'href' => Pi::url($this->url('home'))
        )
    ))
);
/* if (!in_array(Pi::user()->getId(), array(1,7,10))) {
    if ($module != 'user') {
        header("Location: https://www.emrouzkharid.com/index.html");
    }
} */

__('Toman');
?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
<head>
    <meta charset="<?php echo $charset; ?>">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge"><![endif]-->
</head>
<body id="pi-<?php echo $module; ?>" class="pi-locale-<?php echo $locale; ?> pi-front">
<?php if ($module == 'system') { ?>
    <!-- Header: brand, slogan, user bar -->
    <header class="pi-header">
        <div class="pi-header-user">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 text-left">
                        <?php if ($module == 'system') { ?>
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                    <div class="col-md-10">
                        <?php echo $this->widget('system-user-bar'); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-header-body">
            <?php /* <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="clearfix">
                            <nav class="navbar navbar-default row">
                                <div class="navbar-header">
                                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        </div>
        <div class="pi-header-text">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-1 col-md-10">
                        <div class="text-center">
                            <h2>امروز خرید کنید ، فردا پرداخت کنید</h2>
                            <p>با استفاده از سامانه امروز خرید، به راحتی میتوانید خرید مورد نیاز خود را به صورت اعتباری امروز انجام داده و وجه آن را به مرور پرداخت نمایید</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-header-form">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-1 col-md-10">
                        <div class="text-center">
                            <h2>ثبت سفارش کالا</h2>
                            <p>به منظور ثبت سفارش کالا ، لطفا لینک کالا را در فرم زیر وارد نمایید ، همچنین قیمت آن را هم درج نمایید تا حدود پلن های قسط به شما نمایش داده شود</p>
                            <hr />
                        </div>
                    </div>
                    <div class="col-md-offset-2 col-md-8 text-center">
                        <?php echo $this->widget('preorder-form'); ?>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <section class="pi-section">
        <div class="pi-section-box pi-section-box-1">
            <div class="container">
                <div class="row">
                    <div class="pi-section-icon pi-section-icon-w  clearix">
                        <div class="col-md-3 ">
                            <div class="pi-section-icon-single">
                                <a href="https://www.emrouzkharid.com/page/purchase-guide" title="راهنمای خرید">
                                    <img class="hvr-float" alt="راهنمای خرید" src="<?php echo $this->assetTheme('image/icon-1.png'); ?>">
                                </a>
                                <h3>راهنمای خرید</h3>
                                <p>چگونه از خدمات امروز خرید استفاده کنیم ؟</p>
                            </div>
                        </div>
                        <div class="col-md-3 ">
                            <div class="pi-section-icon-single">
                                <a href="https://www.emrouzkharid.com/page/supplier" title="تأمین کننده ما شوید">
                                    <img class="hvr-float" alt="تأمین کننده ما شوید" src="<?php echo $this->assetTheme('image/icon-2.png'); ?>">
                                </a>
                                <h3>تأمین کننده ما شوید</h3>
                                <p>در صورتی که فروشنده کالا یا خدمتی هستید و مایلید مشتریان امروز خرید از خدمات شما استفاده کنند، با ما تماس بگیرید</p>
                            </div>
                        </div>
                        <div class="col-md-3 ">
                            <div class="pi-section-icon-single">
                                <a href="https://www.emrouzkharid.com/page/join-us" title="به ما بپیوندید">
                                    <img class="hvr-float" alt="به ما بپیوندید" src="<?php echo $this->assetTheme('image/icon-3.png'); ?>">
                                </a>
                                <h3>به ما بپیوندید</h3>
                                <p>چنانچه در مجموعه ای مشغول به کار هستید و مایلید همکاران شما از خدمات امروز خرید استفده کنند.</p>
                            </div>
                        </div>
                        <div class="col-md-3 ">
                            <div class="pi-section-icon-single">
                                <a href="https://www.emrouzkharid.com/preorder/checkout" title="انواع طرح های خرید">
                                    <img class="hvr-float" alt="انواع طرح های خرید" src="<?php echo $this->assetTheme('image/icon-4.png'); ?>">
                                </a>
                                <h3>انواع طرح های خرید</h3>
                                <p>از طری های خرید و روش های پرداخت ما مطلع شوید و با دید باز انتخاب کنید</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-banner pi-section-banner-1">
            <div class="pi-section-banner-body">
                <h2>امروز خرید کنید ، فردا پرداخت کنید</h2>
                <p>با استفاده از سامانه امروز خرید، به راحتی میتوانید خرید مورد نیاز خود را به صورت اعتباری امروز انجام داده و وجه آن را به مرور پرداخت نمایید</p>
            </div>
        </div>
        <div class="pi-section-box pi-section-box-2">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <h2>آخرین کالاهای تحویل شده</h2>
                        <hr />
                        <p>آخرین کالاهای تحویل شده را میتوانید از طریق لینک زیر ماشهده نموده و از آخرین سفارشات مشتریان آگاه شوید</p>
                        <br />
                        <div class="clearfix">
                            <div class="pi-custom-product">
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="thumbnail">
                                            <img class="img-responsive" alt="" src="<?php echo $this->assetTheme('image/product-1.jpg'); ?>">
                                            <div class="caption">
                                                <h3>محصول فروخته شده</h3>
                                                <p>تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="thumbnail">
                                            <img class="img-responsive" alt="" src="<?php echo $this->assetTheme('image/product-2.jpg'); ?>">
                                            <div class="caption">
                                                <h3>محصول فروخته شده</h3>
                                                <p>تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست </p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4">
                                        <div class="thumbnail">
                                            <img class="img-responsive" alt="" src="<?php echo $this->assetTheme('image/product-3.jpg'); ?>">
                                            <div class="caption">
                                                <h3>محصول فروخته شده</h3>
                                                <p>تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست تست </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <p class="clearfix">
                            <a class="btn btn-primary btn-lg" href="">بیشتر بخوانید</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-banner pi-section-banner-2 pi-section-icon">
            <div class="pi-section-banner-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 pi-section-icon-single">
                            <img alt="" src="<?php echo $this->assetTheme('image/icon5.png'); ?>">
                            <p><a href="" title="">به گستره ایران</a></p>
                        </div>
                        <div class="col-md-4 pi-section-icon-single">
                            <img alt="" src="<?php echo $this->assetTheme('image/icon6.png'); ?>">
                            <p><a href="" title="">سرعت خرید بالا</a></p>
                        </div>
                        <div class="col-md-4 pi-section-icon-single">
                            <img alt="" src="<?php echo $this->assetTheme('image/icon7.png'); ?>">
                            <p><a href="" title="">امکان بازگشت سرمایه</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-section-box pi-section-box-3">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="pi-custom-feedback">
                            <div class="clearfix text-center">
                                <h2>دیدگاه مشتریان</h2>
                                <hr />
                            </div>
                            <div class="clearfix">
                                <div class="col-md-4">
                                    <div class="pi-custom-feedback-single">
                                        <img class="img-circle" src="<?php echo $this->assetTheme('image/avatar.png'); ?>" alt="">
                                        <h3>آقای مشتری جدید</h3>
                                        <p><i class="fa fa-quote-right" aria-hidden="true"></i> بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. <i class="fa fa-quote-left" aria-hidden="true"></i></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="pi-custom-feedback-single">
                                        <img class="img-circle" src="<?php echo $this->assetTheme('image/avatar.png'); ?>" alt="">
                                        <h3>آقای مشتری جدید</h3>
                                        <p><i class="fa fa-quote-right" aria-hidden="true"></i> بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. <i class="fa fa-quote-left" aria-hidden="true"></i></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="pi-custom-feedback-single">
                                        <img class="img-circle" src="<?php echo $this->assetTheme('image/avatar.png'); ?>" alt="">
                                        <h3>آقای مشتری جدید</h3>
                                        <p><i class="fa fa-quote-right" aria-hidden="true"></i> بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. بهترین سرویس را در سریعترین زمان و مناسب ترین قیمت از امروز خرید دریافت کرده ام. <i class="fa fa-quote-left" aria-hidden="true"></i></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>
<?php } else { ?>
    <header class="pi-header">
        <div class="pi-header-user">
            <div class="container">
                <div class="row">
                    <div class="col-md-2 text-left">
                        <?php if ($module == 'system') { ?>
                            <h1>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h1>
                        <?php } else { ?>
                            <h2>
                                <a href="<?php echo Pi::url($this->url('home')); ?>" title="<?php echo _escape($sitename); ?>">
                                    <img src="<?php echo $this->assetTheme('image/logo.png'); ?>" alt="<?php echo _escape($sitename); ?>">
                                </a>
                            </h2>
                        <?php } ?>
                    </div>
                    <div class="col-md-10">
                        <?php echo $this->widget('system-user-bar'); ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="pi-header-body">
            <?php /* <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="clearfix">
                            <nav class="navbar navbar-default row">
                                <div class="navbar-header">
                                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <?php echo $navigation->menu()->setUlClass('nav navbar-nav pi-navbar-nav'); ?>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div> */ ?>
        </div>
        <?php /* if ($module != 'portfolio') { ?>
        <div class="pi-header-form">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-2 col-md-8 text-center">
                        <?php echo $this->widget('preorder-form', array('order' => 'inline')); ?>
                    </div>
                </div>
            </div>
        </div>
        <?php } */?>
    </header>
    <!-- Page main content: breadcrumb, flash-messenger, blocks and module content -->
    <section class="pi-section">
        <div class="container">
            <div class="pi-main-container">
                <?php if ($breadcrumbs) { echo $breadcrumbs; } ?>
                <!-- Flash messenger -->
                <?php include $this->template('flash-messenger'); ?>
                <!-- Top head zone -->
                <?php if (!empty($blocks['0'])) { ?>
                    <div class="pi-zone-0">
                        <?php foreach ($blocks['0'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
                <div class="row">
                    <!-- Left zone -->
                    <?php if (!empty($blocks['1'])) { ?>
                        <div class="pi-zone-1 col-md-4">
                            <?php foreach ($blocks['1'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                    <div class="<?php
                    if (isset($blocks['1']) && isset($blocks['8'])) {
                        echo 'col-md-4';
                    } elseif (isset($blocks['1']) || isset($blocks['8'])) {
                        echo 'col-md-8';
                    } else {
                        echo 'col-md-12';
                    }
                    ?>">
                        <!-- Center top zone -->
                        <?php if (isset($blocks['2'])) { ?>
                            <div class="pi-zone-2">
                                <?php foreach ($blocks['2'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                        <?php if (isset($blocks['3']) || isset($blocks['4'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-3">
                                    <?php
                                    if (isset($blocks['3'])) {
                                        foreach ($blocks['3'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-4">
                                    <?php
                                    if (isset($blocks['4'])) {
                                        foreach ($blocks['4'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Module content starts -->
                        <?php if (!empty($content)) { ?>
                            <div class="<?php echo $module; ?>">
                                <div class="pi-module-content" data-ng-app="<?php echo $module; ?>">
                                    <?php echo $content; ?>
                                </div>
                                <?php echo Pi::service('comment')->load(array('options' => array('type' => 'js'))); ?>
                            </div>
                        <?php } ?>
                        <!-- Module content ends -->
                        <?php if (isset($blocks['5']) || isset($blocks['6'])) { ?>
                            <div class="row">
                                <div class="col-md-6 pi-zone-5">
                                    <?php
                                    if (isset($blocks['5'])) {
                                        foreach ($blocks['5'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                                <div class="col-md-6 pi-zone-6">
                                    <?php
                                    if (isset($blocks['6'])) {
                                        foreach ($blocks['6'] as $block) {
                                            include $blockTemplate;
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
                        <?php } ?>
                        <!-- Center bottom zone -->
                        <?php if (isset($blocks['7'])) { ?>
                            <div class="pi-zone-7">
                                <?php foreach ($blocks['7'] as $block) {
                                    include $blockTemplate;
                                } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <!-- Right zone -->
                    <?php if (isset($blocks['8'])) { ?>
                        <div class="col-md-4 pi-zone-8">
                            <?php foreach ($blocks['8'] as $block) {
                                include $blockTemplate;
                            } ?>
                        </div>
                    <?php } ?>
                </div>
                <!-- Bottom foot zone -->
                <?php if (isset($blocks['99'])) { ?>
                    <div class="pi-zone-99">
                        <?php foreach ($blocks['99'] as $block) {
                            include $blockTemplate;
                        } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </section>
<?php } ?>
<footer class="pi-footer">
    <div class="pi-footer-social">
        <div class="container">
            <div class="row">
                <div class="col-md-6 pi-footer-social-text">امروز خرید، ارائه دهنده راهکار های سریع خرید کالا</div>
                <div class="col-md-6 text-right">
                    <ul class="list-inline">
                        <li><a href="#" title=""><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-youtube"></i></a></li>
                        <li><a href="#" title=""><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-body">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <p>این فروشگاه کار خود را در سال 1394 آغاز نموده است. با توجه به رشد اقبال عمومی نسبت به خریدهای اینترنتی، فروشگاه امروز خرید محصولات خود را با تمرکز بر کالاهای دیجیتال و لوازم خانگی سبک، به صورت اینترنتی عرضه می‌کند.</p>
                    <p>اما تمایز این فروشگاه نسبت به سایر فروشگاه‌های اینترنتی، ایجاد امکان خرید اعتباری آسان و امن برای مشتریان خود است.</p>
                </div>
                <div class="col-md-2">
                    <h3>راهکار ها</h3>
                    <ul class="list-unstyled">
                        <li><a href="https://www.emrouzkharid.com/page/terms" title="شرایط و مقررات">شرایط و مقررات</a></li>
                        <li><a href="https://www.emrouzkharid.com/page/about-us" title="درباره ما">درباره ما</a></li>
                        <li><a href="https://www.emrouzkharid.com/contact" title="تماس با ما">تماس با ما</a></li>
                    </ul>
                </div>
                <div class="col-md-2">
                    <h3>خدمات</h3>
                    <ul class="list-unstyled">
                        <li><a href="https://www.emrouzkharid.com/page/purchase-guide" title="راهنمای خرید">راهنمای خرید</a></li>
                        <li><a href="https://www.emrouzkharid.com/page/supplier" title="تأمین کننده ما شوید">تأمین کننده ما شوید</a></li>
                        <li><a href="https://www.emrouzkharid.com/page/join-us" title="به ما بپیوندید">به ما بپیوندید</a></li>
                        <li><a href="https://www.emrouzkharid.com/page/methods" title="انواع طرح های خرید">انواع طرح های خرید</a></li>
                    </ul>
                </div>
                <div class="col-md-3 text-center">
                    <ul class="list-inline row">
                        <li class="col-md-6"><img class="img-responsive" id='drftwmcsbrgwhwladrft' style='cursor:pointer' onclick='window.open("https://trustseal.enamad.ir/Verify.aspx?id=18641&p=nbpdaqgwhwmbodshnbpd", "Popup","toolbar=no, location=no, statusbar=no, menubar=no, scrollbars=1, resizable=0, width=580, height=600, top=30")' alt="<?php echo _escape($sitename); ?>" src='https://trustseal.enamad.ir/logo.aspx?id=18641&p=lznbukaqkzoeaodslznb'/></li>
                        <li class="col-md-6"><img class="img-responsive" src="<?php echo $this->assetTheme('image/behpardakht.png'); ?>" alt="<?php echo _escape($sitename); ?>"></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="pi-footer-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6" data-rel="license">تمام حقوق مطالب برای وب سایت <a title="<?php echo _escape($sitename); ?>" href="<?php echo Pi::url($this->url('home')); ?>"><?php echo _escape($sitename); ?></a> محفوظ است.</div>
                <div class="col-md-6 text-right" data-rel="license"> طراحی و توسعه <a title="فراگسترش" href="http://www.faragostaresh.com" target="_blank">فراگسترش</a></div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>